# Generated by Django 3.2.6 on 2021-09-20 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Action_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_desc', models.CharField(max_length=255)),
                ('p_pic', models.FileField(blank=True, null=True, upload_to='pics')),
                ('p_heading', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
